export type InvoiceExpressCountry
  = 'Portugal'
  | 'Ireland'
  | 'UK'
  | 'Canada'
  | 'United States'
  | 'Afghanistan'
  | 'Albania'
  | 'Algeria'
  | 'American Samoa'
  | 'Andorra'
  | 'Angola'
  | 'Anguilla'
  | 'Antigua and Barbuda'
  | 'Argentina'
  | 'Armenia'
  | 'Aruba'
  | 'Australia'
  | 'Austria'
  | 'Azerbaijan'
  | 'Bahamas'
  | 'Bahrain'
  | 'Bangladesh'
  | 'Barbados'
  | 'Belarus'
  | 'Belgium'
  | 'Belize'
  | 'Benin'
  | 'Bermuda'
  | 'Bhutan'
  | 'Bolivia'
  | 'Bosnia-Herzegovina'
  | 'Botswana'
  | 'Brazil'
  | 'British Indian Ocean Territory'
  | 'Brunei'
  | 'Bulgaria'
  | 'Burkina Faso'
  | 'Burma'
  | 'Burundi'
  | 'Cambodia'
  | 'Cameroon'
  | 'Canton and Enderbury Islands'
  | 'Cape Verde'
  | 'Cayman Islands'
  | 'Central African Republic'
  | 'Chad'
  | 'Chile'
  | 'China'
  | 'Christmas Island'
  | 'Cocos (Keeling) Islands'
  | 'Colombia'
  | 'Comoros'
  | 'Congo'
  | 'Congo, Democratic Republic'
  | 'Cook Islands'
  | 'Costa Rica'
  | 'Côte d’Ivoire'
  | 'Croatia'
  | 'Cuba'
  | 'Curyprus'
  | 'Czech Republic'
  | 'Denmark'
  | 'Djibouti'
  | 'Dominica'
  | 'Dominican Republic'
  | 'Dronning Maud Land'
  | 'East Timor'
  | 'Ecuador'
  | 'Egypt'
  | 'El Salvador'
  | 'Equatorial Guinea'
  | 'Eritrea'
  | 'Estonia'
  | 'Ethiopia'
  | 'Faeroe Islands (Føroyar)'
  | 'Falkland Islands'
  | 'Fiji'
  | 'Finland'
  | 'France'
  | 'French Guiana'
  | 'French Polynesia'
  | 'Gabon'
  | 'Gambia'
  | 'Georgia'
  | 'Germany'
  | 'Ghana'
  | 'Gibraltar'
  | 'Great Britain'
  | 'Greece'
  | 'Greenland'
  | 'Grenada'
  | 'Guadeloupe'
  | 'Guam'
  | 'Guatemala'
  | 'Guernsey'
  | 'Guinea-Bissau'
  | 'Guinea'
  | 'Guyana'
  | 'Haiti'
  | 'Heard and McDonald Islands'
  | 'Honduras'
  | 'Hong Kong'
  | 'Hungary'
  | 'Iceland'
  | 'India'
  | 'Indonesia'
  | 'International Monetary Fund'
  | 'Iran'
  | 'Iraq'
  | 'Isle of Man'
  | 'Israel'
  | 'Italy'
  | 'Ivory Coast'
  | 'Jamaica'
  | 'Japan'
  | 'Jersey'
  | 'Johnston Island'
  | 'Jordan'
  | 'Kampuchea'
  | 'Kazakhstan'
  | 'Kenya'
  | 'Kiribati'
  | 'Korea, North'
  | 'Korea, South'
  | 'Kuwait'
  | 'Kyrgyzstan'
  | 'Laos'
  | 'Latvia'
  | 'Lebanon'
  | 'Lesotho'
  | 'Liberia'
  | 'Libya'
  | 'Liechtenstein'
  | 'Lithuania'
  | 'Luxembourg'
  | 'Macau'
  | 'Macedonia (Former Yug. Rep.)'
  | 'Madagascar'
  | 'Malawi'
  | 'Malaysia'
  | 'Maldives'
  | 'Mali'
  | 'Malta'
  | 'Marshall Islands'
  | 'Martinique'
  | 'Mauritania'
  | 'Mauritius'
  | 'Mayotte'
  | 'Micronesia'
  | 'Midway Islands'
  | 'Mexico'
  | 'Moldova'
  | 'Monaco'
  | 'Mongolia'
  | 'Montenegro'
  | 'Montserrat'
  | 'Morocco'
  | 'Mozambique'
  | 'Myanmar'
  | 'Nauru'
  | 'Namibia'
  | 'Nepal'
  | 'Netherlands Antilles'
  | 'Netherlands'
  | 'New Caledonia'
  | 'New Zealand'
  | 'Nicaragua'
  | 'Niger'
  | 'Nigeria'
  | 'Niue'
  | 'Norfolk Island'
  | 'Northern Mariana Islands'
  | 'Norway'
  | 'Oman'
  | 'Pakistan'
  | 'Palau'
  | 'Palestine'
  | 'Panama'
  | 'Papua New Guinea'
  | 'Paraguay'
  | 'Peru'
  | 'Philippines'
  | 'Pitcairn Island'
  | 'Poland'
  | 'Puerto Rico'
  | 'Qatar'
  | 'Reunion'
  | 'Romania'
  | 'Russia'
  | 'Rwanda'
  | 'Samoa (Western)'
  | 'Samoa (America)'
  | 'San Marino'
  | 'São Tomé and Príncipe'
  | 'Saudi Arabia'
  | 'Sénégal'
  | 'Serbia'
  | 'Seychelles'
  | 'Sierra Leone'
  | 'Singapore'
  | 'Slovakia'
  | 'Slovenia'
  | 'Solomon Islands'
  | 'Somalia'
  | 'South Africa'
  | 'Spain'
  | 'Sri Lanka'
  | 'St. Helena'
  | 'St. Kitts and Nevis'
  | 'St. Lucia'
  | 'St. Vincent and the Grenadines'
  | 'Sudan'
  | 'Suriname'
  | 'Svalbard and Jan Mayen Islands'
  | 'Swaziland'
  | 'Sweden'
  | 'Switzerland'
  | 'Syria'
  | 'Tahiti'
  | 'Taiwan'
  | 'Tajikistan'
  | 'Tanzania'
  | 'Thailand'
  | 'Timor-Leste'
  | 'Togo'
  | 'Trinidad and Tobago'
  | 'Tunisia'
  | 'Turkey'
  | 'Turkmenistan'
  | 'Turks and Caicos Islands'
  | 'Tuvalu'
  | 'Uganda'
  | 'Ukraine'
  | 'United Arab Emirates'
  | 'Upper Volta'
  | 'Uruguay'
  | 'Uzbekistan'
  | 'Vanuatu'
  | 'Vatican'
  | 'Venezuela'
  | 'Vietnam'
  | 'Virgin Islands'
  | 'Wake Island'
  | 'Wallis and Futuna Islands'
  | 'Western Sahara'
  | 'Western Samoa'
  | 'Yemen'
  | 'Zaïre'
  | 'Zambia'
  | 'Zimbabwe'
  ;

export enum InvoiceExpressCountryCode
  { PortugalCode = 1
  , IrelandCode  = 2
  , UKCode       = 3
  }
